services:
  api-db:
    container_name: api-db
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - api-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  airflow-db:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=new_username
      - POSTGRES_PASSWORD=new_password
      - POSTGRES_DB=new_database_name
    volumes:
      - airflow-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5433:5432"
    restart: always
volumes:
  api-db-volume:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: ${API_DB_VOLUMES}
  airflow-db-volume:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: ${AIRFLOW_DB_VOLUMES}